### ISSUE TITLE
Clean up abstract trees

### ISSUE THREAD

**Issue by jotok** [aws/random-cut-forest-by-aws#116]
* AbstractRandomCutTreeFields should be protected instead of public
* AbstractCompactRandomCutTree sets the enableCache variable, even though it's already set in the super constructor
* The second constructor in AbstractCompactRandomCutTree (the one used to restore from state) should be able to restore sequence indexes.
* Should `enableCache` be changed to `enableBoundingBoxCache`, or is there a plant o reuse that variable for other kinds of caching?

**Comment by sudiptoguha** [comment]
Mostly done.
