### ISSUE TITLE
Review naming conventions for tree update methods

### ISSUE THREAD

**Issue by jotok** [aws/random-cut-forest-by-aws#119]
* `increaseMassOfAncestorsAndItself` is a little awkward
* `constructBoxInPlace` is ambiguous, because `construct` makes it sound like a new allocation, but `InPlace` suggests that it's updating the existing box (which is true).
* We have both `recoompute` and `reCompute` in different places.

**Comment by sudiptoguha** [comment]
Some of these have been fixed but tabling the more general question "what should be the tree update be". The question would likely be revisited for a revamp.
