### ISSUE TITLE
Convert floating point numbers to bytes in JSON serde

### ISSUE THREAD

**Issue by jotok** [aws/random-cut-forest-by-aws#124]
Serializing a floating point value to a string of digits can result in rounding errors, which could in turn result in an invalid tree state during deserialization. We should write a custom serde that converts floating point numbers to lists of bytes for lossless serialization.

**Comment by wnbts** [comment]
json doesn't support binary data type. Using a binary format makes sense. Or the binary in json must be encoded and decoded.

**Comment by jotok** [comment]
The approach I'm working on right now is to create customer type adapters for the `float[]` and `double[]` types where we use hex strings to represent the exact binary content of a given floating point value.

**Comment by jotok** [comment]
Rather than convert a floating-point value to a list of byte values, we can use the [Double.toHexString(double)](https://docs.oracle.com/javase/8/docs/api/java/lang/Double.html#toHexString-double-) method to write the double as a String in a lossless way. While playing around with this approach, we found some ways to reduce the size of the generated JSON:

1. The hex string representation of 0 is `"0x0.0p0"` (including quotations marks), compared to `0.0` for the standard representation. Since the point store is created to contain the maximum possible number of points, it will mostly be filled with 0s until the forest has been running for a long time. And since the point store is a large part of serialized object size, serializing 0 as `"0x0.0p0"` can result in much larger JSON files, up to 2x in some experiments. I wrote a wrapper around `toHexString` to detect 0s and output `"0"` instead, and the resulting JSON was comparable to or smaller than the JSON using the default floating point format.
2. We  can save additional bytes in the output string by concatenating the array elements into a single string in the output. E.g., we write `"x,y,z"` instead of `["x", "y", "z"]`.
3. We can save even more space by encoding shorts and ints as hex strings.

We're making lossless serialization of floating-point numbers a requirement. My question is: should we take either of these additional steps to reduce the size of the JSON output created by `RandomCutForestSerDe`?

1. Should we encode 0s as `"0"` instead of `"0x0.0p0"`?
2. Should we output an array of floating point values as a single string?
3. Should we output ints and shorts as hex strings?

**Comment by wnbts** [comment]
my thoughts. special encodings may also make decoding harder.

1. 0 is ok. What to do with other integral values such as 1?
2. a string with separators?
3. if the decoder knows the type, it should be ok.

**Comment by wnbts** [comment]
and is the goal to optimize space over time?

**Comment by jotok** [comment]
I'm actually reading about this more right now, and it looks like the standard `Double.toString` method will write enough digits so that the original floating-point value can be recovered exactly:

> How many digits must be printed for the fractional part of m or a? There must be at least one digit to represent the fractional part, and beyond that as many, but only as many, more digits as are needed to uniquely distinguish the argument value from adjacent values of type double. That is, suppose that x is the exact mathematical value represented by the decimal representation produced by this method for a finite nonzero argument d. Then d must be the double value nearest to x; or if two double values are equally close to x, then d must be one of them and the least significant bit of the significand of d must be 0.

So I believe now that no change is necessary to support lossless JSON serialization (and this is supported by some unit test experiments).

My personal inclination is to prefer "vanilla" JSON output unless we feel that there's a strong case to optimize for the output size.

**Comment by jotok** [comment]
After thinking it over, I'm going to close this issue as "will not implement" (but feel free to reopen if you still think it's worth discussing). I think it makes sense for the library to ship with an encoder that produces vanilla JSON, and users can create custom encoders if they need specific optimizations. I'll add unit tests to serialization package to confirm that floating point numbers can be serialized and restored exactly using the default representation.
