### ISSUE TITLE
Intermittent failure in RandomCutForestSerDeTests

### ISSUE THREAD

**Issue by jotok** [aws/random-cut-forest-by-aws#20]
I'm seeing an occasional failuree in the RandomCutForestSerDeTests class. The tests usually pass on re-run. I'm creating this issue to track occurrences.

Example
```
[ERROR] Tests run: 16, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 22.914 s <<< FAILURE! - in com.amazon.randomcutforest.serialize.RandomCutForestSerDeTests
[ERROR] toJsonString{int, int, int, int, int, int, int}[9]  Time elapsed: 0.55 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <1.394635311942881> but was: <1.8229730367398675>
        at com.amazon.randomcutforest.serialize.RandomCutForestSerDeTests.toJsonString(RandomCutForestSerDeTests.java:75)
```

**Comment by wnbts** [comment]
I tried multiple times locally but could not produce failures. When this issue re-occurs, the configuration for the failed test cases can be recorded in this issue.

**Comment by wnbts** [comment]
Looks like this issue hasn't occurred for a while. Closing for now.
