### ISSUE TITLE
Test failures with OpenJDK 13

### ISSUE THREAD

**Issue by jotok** [aws/random-cut-forest-by-aws#22]
Unit tests are failing when being run under OpenJDK 13 with the following error message:

```
[ERROR] testImputeMissingValuesWithNoMissingValues  Time elapsed: 0.001 s  <<< ERROR!
java.lang.RuntimeException: Internal error: Failed to find the "modifiers" field in method setInternalState.
	at com.amazon.randomcutforest.RandomCutForestTest.setUp(RandomCutForestTest.java:82)
Caused by: java.lang.NoSuchFieldException: modifiers
	at com.amazon.randomcutforest.RandomCutForestTest.setUp(RandomCutForestTest.java:82)
```

```
$ java --version
openjdk 13.0.2 2020-01-14
OpenJDK Runtime Environment (build 13.0.2+8)
OpenJDK 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)
```

**Comment by jotok** [comment]
Here is an issue on Powermock describing similar behavior, but it was closed as "fixed" in 2018.
https://github.com/powermock/powermock/issues/939

**Comment by jdecuyper** [comment]
The error is thrown when calling `Whitebox.setInternalState`.

Initially I suspected that JDK 13 was preventing Powermock to override protected final fields. Then I downloaded JDK 13, created a vanilla project with a basic version of the forest and the executor and in the end managed to successfully run the following test:

```
package com.amazon.narx;

import org.junit.Test;
import org.powermock.reflect.Whitebox;
import static org.junit.Assert.assertEquals;

public class RandomCutForestTest {

    @Test
    public void test_intakeDataFromUrl() throws Exception {
        RandomCutForest forest = new RandomCutForest();

        assertEquals(false, forest.storeSequenceIndexesEnabled);
        assertEquals(42, forest.executor.getTotalUpdates());

        AbstractForestTraversalExecutor executor = new SequentialForestTraversalExecutor(678);
        Whitebox.setInternalState(forest, "storeSequenceIndexesEnabled", true);
        Whitebox.setInternalState(forest, "executor", executor);

        assertEquals(true, forest.storeSequenceIndexesEnabled);
        assertEquals(678, forest.executor.getTotalUpdates());
    }
}
```
I used the following dependencies:

```
junit:junit:4.13
org.powermock:powermock-reflect:2.0.7
```

Now, taking a closer at the dependencies maven downloaded locally, I found `org.powermock:powermock-reflect:2.0.2` which is a couple of minor releases behind. If I force the version to be 2.0.7 in the pom.xml file then `mvn package` succeeds.  

So it seems the only change needed is to change [this line](https://github.com/aws/random-cut-forest-by-aws/blob/master/Java/pom.xml#L70) from `2.0.2` to `2.0.7`. I will confirm using another host and if it is successful launch a PR.
