### ISSUE TITLE
Ready for production

### ISSUE THREAD

**Issue by vidbap** [aws/random-cut-forest-by-aws#23]
Hi,

We are building a multi-cloud anomaly detector application with two deployment options for our SaaS ops.  We plan to use Random Cut Forest in Sagemaker when running in AWS while use this opensource when running on-premise or private cloud due to data sensitivity issues when we cannot send data to cloud through estimator APIs when invoking Sagemaker APIs.  

Would you please let me know if random-cut-forest-by-aws  (this repo) is ready for production and any differences from Sagemaker in terms of functionality such as explainability and real-time streaming use cases?  I saw a note [in Development] in the title and hence wondering the status and when it will be production ready.  Again great work on this repo.

Thanks.

**Comment by jotok** [comment]
The Random Cut Forest library has been designed and tested for production use. It's built to support anomaly detection out of the box with attribution and streaming use cases.
Anomaly detection functionality based on this library will be available as part of Open Distro for Elasticsearch in April.
 
For information regarding SageMaker, please reach out to the corresponding service teams, as well the latest pages here https://docs.aws.amazon.com/sagemaker/latest/dg/randomcutforest.html
