### ISSUE TITLE
Proposal: new directory structure to multiple language implementations

### ISSUE THREAD

**Issue by jotok** [aws/random-cut-forest-by-aws#28]
We are currently developing a second implementation of RCFs in C. We intend to support both the Java and C versions going forward, since the two implementations have different tradeoffs. This issue is to discuss how we should reorganize the project directory to accomodate both implementations.

**Proposal 1**: Root level language directories
```
c/
java/
python/
```
With this approach, the existing Maven project would be moved to a new java/ subdirectory, and we would add a top-level c/ directory to contain the C implementation. We could then continue this pattern for other language bindings. For example, the python/ directory could contain a Python project with bindings to the C library.

If we take this approach we'll have to create a new top-level README explaining the setup and possibly giving some information about RCF the algorithm. We'll also have to double-check that we can execute our github workflow from a subdirectory.

**Proposal 2**: Separate repositories

This proposal is to create a new repository for the C implementation. This approach would all both repos to conform to the standard project layout wherein the root directory for the project contains the build configuration files for your project.

By taking this approach we would lose some discoverability between the two implementations, and it would be less clear that the two implementations conform to a single "vision" for RCFs.

**Also considered**: Add the C library to a directory in the Maven project
```
benchmark/
core/
...
rcfc/
```
In this approach, the folder containing the C code would live in the Maven project, but it would be ignored by the Maven build. I think the main drawback here is that the C and Java versions would not appear as different-but-equally-good implementations. People who get to the repository via search might not even notice that there is a C implementation.

**Comment by wnbts** [comment]
how about separate packages for java and cpp implementations? apache datasketch is an example of using [java](https://github.com/apache/incubator-datasketches-java) and [cpp+python binding](https://github.com/apache/incubator-datasketches-cpp)

**Comment by jotok** [comment]
I think that's another good option, and I think it's the option that would conform to most people's expectations about the scope of a single repository. The argument against this approach is that we want to convey that these two implementations are both attempting to implement the same "vision" for RCFs, and we will try to keep the respective core libraries feature compatible. I'll add "separate repos" as another option for discussion.

**Comment by jotok** [comment]
In offline discussion, we have agreed to follow proposal 1 for now. We can choose to split the C library into its own repository in the future if it begins to significantly diverge from the Java implementation.

In order to implement this change, we need a new top-level README file which explains the RCF algorithm at a high level and describes the two implementations. @sudiptoguha is working on this, and once we have a draft we'll create a new PR to close this issue.
