### ISSUE TITLE
Review default forest parameters

### ISSUE THREAD

**Issue by jotok** [aws/random-cut-forest-by-aws#29]
Before pushing to Maven, let's review and update the default forest parameters. Current defaults:

| Parameter Name | Type | Description | Default Value|
| --- | --- | --- | --- |
| centerOfMassEnabled | boolean | If true, then tree nodes in the forest will compute their center of mass as part of tree update operations. | false |
| dimensions | int | The number of dimensions in the input data. | Required, no default value |
| lambda | double | The decay factor (lambda value) used by stream samplers in this forest. | 1e-5 |
| numberOfTrees | int | The number of trees in this forest. | 100 |
| outputAfter | int | The number of points required by stream samplers before results are returned. | 0.25 * sampleSize |
| parallelExecutionEnabled | boolean | If true, then the forest will create an internal threadpool. Forest updates and traversals will be submitted to this threadpool, and individual trees will be updated or traversed in parallel. | true |
| randomSeed | long | A seed value used to initialize the random number generators in this forest. | |
| sampleSize | int | The sample size used by stream samplers in this forest | 256 |
| storeSequenceIndexesEnabled | boolean | If true, then sequence indexes (ordinals indicating when a point was added to a tree) will be stored in the forest along with poitn values. | false |
| threadPoolSize | int | The number of threads to use in the internal threadpool. | Number of available processors - 1 |
| windowSize | int | An alternate way of specifying the lambda value. Using this parameter will set lambda to 1 / windowSize. | |

To discuss:
* Given what we know about convergence of anomaly scores, 100 trees is probably to many for a default. Proposal: 50.
* Should we change the default for parallel execution to false? From our benchmark results for 50 trees, parallel execution only consistently wins for 256 dimensional points.
* The lambda value in this code was taken from an older implementation and not re-examined. Can we pick a better default? What guidance can we give to users to help them pick a meaningful value?
* I like the idea of windowSize as a more user-friendly way of setting lambda, but does it have a precise mathematical interpretation that we can explain? If not, could we come up with a better choice for a user-friendly setting? For example, something like: "if you set this parameter to 100, then the probability that more than half of your in-sample points comes from the last 100 submitted points is greater than 90%".

**Comment by wnbts** [comment]
1. 50 is fine. is there any benchmarking dataset?
2. yes.
3/4. math is hard. my guess it might depend on a. lambda/window size range, and b. specific implementation to be summarized into one/multiple bounds.

**Comment by sudiptoguha** [comment]
The weight of an element is exp(-lambda*age). It is similar to a notion of half-life; for lambda = 0.001, the relevance of a historical point seen 2000 steps back is exp(-2) vis-a-vis the relevance most recently observed point. Relevance corresponds to being included in the sample (excluding the effect of initial few samples). Lambda = 0 is uniform random sampling from a reservoir.

**Comment by wnbts** [comment]
customers come with a question like i want (with probability z) x data points are sampled from the most recent y steps/points. what lambda should i use? the math behind it appears not trivial enough that we used monte carlo to solve it.

**Comment by jotok** [comment]
Do you think it would be better to set the default lambda to 0, so that users don't just assume that whatever nonzero value we pick is appropriate for their use case?

**Comment by wnbts** [comment]
lambda 0 is at least slightly less arbitrary than current value. A reelated minor issue would be the window size.

**Comment by jotok** [comment]
So we are currently agreed that:
* Default number of trees changes to 50
* Parallel execution changes to false
* Default lambda changes to 0 and we make the following documentation improvements
  * Call out the fact that setting lambda to 0 is not appropriate for most uses
  * Provide better guidance on how to set the lambda value. @cswiercz will try to come up with a rule of thumb that we can share.
