### ISSUE TITLE
Add memory estimation

### ISSUE THREAD

**Issue by ylwu-amzn** [aws/random-cut-forest-by-aws#295]
It will be good if we can know how much memory a model will use to evaluate if we have enough memory to run a new model. AD estimates memory usage https://github.com/opensearch-project/anomaly-detection/blob/a79028f8ee2098fa94e5e4b8ba81affce24b2b8c/src/main/java/org/opensearch/ad/MemoryTracker.java#L261. Now we are going to integrate RCF in MLCommons, that means we need to copy the same code to MLCommons. How about we build memory estimation in this RCF lib directly?

**Comment by sudiptoguha** [comment]
No. As stated "AD estimates memory usage..." that belongs in AD. AD should perform benchmarking.
