### ISSUE TITLE
Add more document

### ISSUE THREAD

**Issue by ylwu-amzn** [aws/random-cut-forest-by-aws#296]
We are adding more and more interesting features to this library like `ForestMode` and `ThresholdedRandomCutForest`. But seems there are little doc to explain how to use these new feature/parameters correctly. Yes, we can learn from the code directly, but that takes time and not efficient especially when people just want to use RCF directly rather than develop code. Will highly appreciate it if anyone can add more tutorial documents with some example code. For example, how to use RCF to do non-time-series anomaly detection or population analysis, and how to use RCF to forecast and what's the limitation.

**Comment by sudiptoguha** [comment]
likely resolved with PR 333.
