### ISSUE TITLE
Publish latest code to maven

### ISSUE THREAD

**Issue by ylwu-amzn** [aws/random-cut-forest-by-aws#301]
Now [AD](https://github.com/opensearch-project/anomaly-detection/tree/1.3/lib) and [ml-commons](https://github.com/opensearch-project/ml-commons/tree/1.3/ml-algorithms/lib) are using local jar dependency to use latest RCF code. This is not best practice. How about we publish the latest RCF code to maven to remove such local jar dependency?

Related issue https://github.com/opensearch-project/index-management/issues/123

**Comment by dblock** [comment]
https://github.com/opensearch-project/anomaly-detection/issues/433

**Comment by dblock** [comment]
I opened https://github.com/aws/random-cut-forest-by-aws/issues/303 to get a CI/CD pipeline instead of doing it by hand.

**Comment by sudiptoguha** [comment]
A CI/CD pipeline would be a great improvement.

**Comment by sudiptoguha** [comment]
closed
