### ISSUE TITLE
[Blog] post contains two identical paragraphs

### ISSUE THREAD

**Issue by olegchorny** [aws/random-cut-forest-by-aws#38]
Hi @sudiptoguha 
I din't manage to find you at linkedin, so I've decided to leverage this repo to report about the finding. This post contains two identical paragraphs: https://opendistro.github.io/for-elasticsearch/blog/odfe-updates/2019/11/random-cut-forests/

![image](https://user-images.githubusercontent.com/20322896/83533510-56016c80-a4f8-11ea-8959-aa0ff45ab173.png)

Thanks for your work!

**Comment by sudiptoguha** [comment]
Thank you! Fixed. Please do not hesitate to point out other issues as well!
