### ISSUE TITLE
deprecate master branch

### ISSUE THREAD

**Issue by wnbts** [aws/random-cut-forest-by-aws#46]
The name "master" is founded on inequality. Since it is used as the name of the most current branch, it is inevitable for contributors to use it for pulling/pushing. For current or potential contributors, this may be or may have been a source of discomfort/rejection, against [Code of Conduct](https://opendistro.github.io/for-elasticsearch/codeofconduct.html). Neutral names such as "main" have been proposed and used.

The [RFC](https://tools.ietf.org/id/draft-knodel-terminology-00.html) provides reasonable arguments against this language. [Github](https://www.bbc.com/news/technology-53050955) , as well as [many others](https://www.forbes.com/sites/elanagross/2020/07/03/twitter-and-jpmorgan-chase-are-the-latest-companies-to-remove-terms-master-and-slave-from-programming-code/#68da80223ced) , are taking the actions to end the use of the term.

**Comment by jotok** [comment]
Thanks for creating this issue, let's make the change.

**Comment by jotok** [comment]
I executed the steps in [this guide](https://dev.to/afrodevgirl/replacing-master-with-main-in-github-2fjf) to move the commit history from 'master' to 'main', push 'main' to github, and set 'main' as the default branch. Let's leave 'master' up for a couple days so people can sync, and if everything looks good we can delete it.

**Comment by wnbts** [comment]
Thank you so much, @jotok !

**Comment by jotok** [comment]
I've deleted the 'master' branch.
